import os from 'node:os';
import { randomUUID } from 'node:crypto';
import { fetchJson, fetchText, safeUrl } from '../http/client.js';
import { canWriteConfig } from '../auth/policy.js';
import { renderText } from '../renderer/service.js';

const text = (args) => (args || []).join(' ').trim();
const action = (args) => String(args?.[0] || '').toLowerCase();
const idOf = (event) => String(event?.userId || 'unknown');
const scopeOf = (event) => String(event?.groupId || 'private');
const list = (value) => Array.isArray(value) ? value : [];
const trim = (value, max = 500) => String(value || '').trim().slice(0, max);
const formatUptime = (seconds) => { let n = Math.floor(Number(seconds || 0)); const d = Math.floor(n / 86400); n %= 86400; const h = Math.floor(n / 3600); n %= 3600; const m = Math.floor(n / 60); return `${d ? `${d}d ` : ''}${h ? `${h}h ` : ''}${m ? `${m}m ` : ''}${n % 60}s`; };
const help = (manifest, usage) => `#\u4e91\u9526${manifest.command} ${usage}`.trim();
const title = (manifest) => `YunJin ${manifest.id} ${manifest.name}`;

async function readState(runtime) { const state = await runtime.stateRepository.read({ version: 1, features: {} }); state.features = state.features && typeof state.features === 'object' ? state.features : {}; return state; }
async function updateFeature(runtime, id, updater) { return runtime.stateRepository.update({ version: 1, features: {} }, async (state) => { state.features = state.features && typeof state.features === 'object' ? state.features : {}; const current = state.features[id] && typeof state.features[id] === 'object' ? state.features[id] : { items: [] }; const result = await updater(current, state); state.features[id] = current; return result; }); }
async function getFeature(runtime, id) { const state = await readState(runtime); return state.features[id] && typeof state.features[id] === 'object' ? state.features[id] : { items: [] }; }
function show(manifest, data) { const rows = list(data.items); if (!rows.length) return `${title(manifest)}\n\u6682\u65e0\u8bb0\u5f55\u3002\n\u7528\u6cd5\uff1a#\u4e91\u9526${manifest.command} \u6dfb\u52a0 <\u5185\u5bb9>`; return `${title(manifest)}\n${rows.slice(0, 20).map((item, index) => `${index + 1}. ${item.text || item.value || item.url || item.id || JSON.stringify(item)}`).join('\n')}`; }

export async function executeFeature(manifest, event, args, runtime) {
  const id = manifest.id; const cmd = action(args); const value = trim(args.slice(1).join(' '));
  if (id === '01') { const memory = process.memoryUsage(); const enabled = runtime.registry.list(event).filter((x) => x.enabled).length; return renderText(['YunJin \u8fd0\u884c\u72b6\u6001', `\u8fd0\u884c\u65f6\u95f4\uff1a${formatUptime(process.uptime())}`, `\u5185\u5b58\uff1a${Math.round(memory.rss / 1024 / 1024)} MB`, `\u5df2\u542f\u7528\uff1a${enabled}/50`, `Node\uff1a${process.version}`, `\u5e73\u53f0\uff1a${os.platform()}`].join('\n')); }
  if (id === '02') { if (!value) return show(manifest, await getFeature(runtime, id)); await updateFeature(runtime, id, (data) => { data.items.unshift({ id: randomUUID(), text: value, userId: idOf(event), time: Date.now() }); data.items = data.items.slice(0, 200); return true; }); await runtime.audit.record({ action: 'error.report', featureId: id, userId: idOf(event) }); return '\u5f02\u5e38\u5df2\u8bb0\u5f55\u3002'; }
  if (id === '03') { await runtime.audit.record({ action: 'log.view', featureId: id, userId: idOf(event) }); return show(manifest, await getFeature(runtime, id)); }
  if (id === '04') { if (cmd === '\u5f00\u59cb' || cmd === 'start') { const tx = { id: randomUUID(), text: value || 'default', status: 'active', startedAt: Date.now(), userId: idOf(event) }; await updateFeature(runtime, id, (data) => { data.items.unshift(tx); return true; }); return `\u4e8b\u52a1\u5df2\u5f00\u59cb\uff1a${tx.id}`; } const data = await getFeature(runtime, id); const tx = data.items.find((item) => item.id === args[1] || item.text === value); if (!tx) return help(manifest, '\u5f00\u59cb <\u540d\u79f0>|\u7ed3\u675f <ID>'); tx.status = cmd === '\u5931\u8d25' || cmd === 'fail' ? 'failed' : 'done'; tx.finishedAt = Date.now(); tx.durationMs = tx.finishedAt - tx.startedAt; await updateFeature(runtime, id, (next) => { next.items = data.items; return true; }); return `\u4e8b\u52a1\u5df2\u7ed3\u675f\uff1a${tx.id} ${tx.durationMs}ms`; }
  if (id === '05') { const data = await getFeature(runtime, id); if (cmd === '\u6dfb\u52a0' || cmd === 'add') { try { safeUrl(args[1]); } catch (error) { return `URL \u88ab\u62d2\u7edd\uff1a${error.message}`; } const item = { id: randomUUID(), url: args[1], status: 'unknown' }; await updateFeature(runtime, id, (next) => { next.items = [item, ...data.items]; return true; }); return `\u76d1\u63a7\u5df2\u6dfb\u52a0\uff1a${item.id}`; } if (cmd === '\u68c0\u67e5' || cmd === 'check') { const item = data.items.find((x) => x.id === args[1]) || data.items[0]; if (!item) return help(manifest, '\u6dfb\u52a0 <URL>|\u68c0\u67e5 <ID>'); const started = Date.now(); try { await fetchText(item.url, { maxBytes: 4096 }); item.status = 'up'; item.latency = Date.now() - started; } catch (error) { item.status = 'down'; item.error = error.message; } await updateFeature(runtime, id, (next) => { next.items = data.items; return true; }); return `${item.url}\n\u72b6\u6001\uff1a${item.status}\n\u5ef6\u8fdf\uff1a${item.latency || '-'}ms`; } return show(manifest, data); }
  if (id === '06' || id === '21' || id === '35') { if (!args.length || cmd === '\u5217\u8868' || cmd === 'list') return `${title(manifest)}\n${(await runtime.scheduler.list()).filter((item) => item.featureId === id).map((item) => `${item.id} ${item.status} ${new Date(item.runAt).toLocaleString()}`).join('\n') || '\u6682\u65e0\u4efb\u52a1'}`; if (cmd === '\u53d6\u6d88' || cmd === 'cancel') return await runtime.scheduler.cancel(args[1]) ? '\u4efb\u52a1\u5df2\u53d6\u6d88\u3002' : '\u672a\u627e\u5230\u4efb\u52a1\u3002'; const minutes = Number(args[1]); if (!Number.isFinite(minutes) || minutes <= 0) return help(manifest, '\u6dfb\u52a0 <\u5206\u949f> <\u5185\u5bb9>'); const task = await runtime.scheduler.create({ featureId: id, title: value || '\u63d0\u9192', delayMs: minutes * 60000, payload: { groupId: event.groupId, userId: event.userId, content: value } }); return `\u4efb\u52a1\u5df2\u521b\u5efa\uff1a${task.id}`; }
  if (id === '07') { const manifests = runtime.registry.list(event).filter((item) => item.enabled); return ['YunJin \u5e2e\u52a9', '', ...manifests.map((item) => `#\u4e91\u9526${item.command}  ${item.name} [${item.access}]`)].join('\n'); }
  if (id === '08') { if (!args.length || cmd === '\u67e5\u770b' || cmd === 'view') return (await runtime.config.describeEffective(event)).values; if (cmd === '\u91cd\u8f7d' || cmd === 'reload') return runtime.config.reload(); if (cmd === '\u6821\u9a8c' || cmd === 'validate') return runtime.config.validate(); const scopeName = args[1] || 'global'; const key = args[2]; if (cmd === '\u83b7\u53d6' || cmd === 'get') return runtime.config.getEffectiveValue({ name: scopeName, id: args[3] }, key); if (cmd === '\u8bbe\u7f6e' || cmd === 'set') { if (!canWriteConfig(event, { name: scopeName, id: args[3] })) return '\u4ec5 Yunzai OP \u53ef\u4fee\u6539\u5168\u5c40\u914d\u7f6e\u3002'; let parsed; try { parsed = JSON.parse(args.slice(3).join(' ')); } catch { return '\u914d\u7f6e\u503c\u5fc5\u987b\u662f JSON\u3002'; } return runtime.config.set({ name: scopeName, id: args[3] }, key, parsed); } return help(manifest, '\u67e5\u770b|\u83b7\u53d6|\u8bbe\u7f6e|\u91cd\u8f7d|\u6821\u9a8c'); }
  if (id === '09') return `\u5f53\u524d\u8eab\u4efd\uff1a${event.isMaster ? 'OP' : event.role || '\u666e\u901a\u7528\u6237'}\n\u7fa4\u53f7\uff1a${event.groupId || '\u79c1\u804a'}\n\u6743\u9650\u6a21\u578b\uff1aYunzai OP + \u7fa4\u7ba1\u7406\u5458`;
  if (id === '15' || id === '16') { const data = await getFeature(runtime, id); if (cmd === '\u6dfb\u52a0' || cmd === 'add') { await updateFeature(runtime, id, (next) => { next.items = [value, ...list(data.items).filter((item) => item !== value)]; return true; }); return '\u5173\u952e\u8bcd\u5df2\u6dfb\u52a0\u3002'; } if (cmd === '\u5220\u9664' || cmd === 'del') { await updateFeature(runtime, id, (next) => { next.items = list(data.items).filter((item) => item !== args[1]); return true; }); return '\u5173\u952e\u8bcd\u5df2\u5220\u9664\u3002'; } return show(manifest, data); }
  if (id === '17') { const ids = args.flatMap((item) => item.split(',')).filter(Boolean).slice(0, 20); let done = 0; const bot = event.raw?.bot || event.raw?.runtime?.bot; for (const messageId of ids) { try { if (typeof bot?.deleteMsg === 'function') { await bot.deleteMsg(messageId); done += 1; } } catch {} } return `\u5df2\u5904\u7406 ${done}/${ids.length} \u6761\u64a4\u56de\u8bf7\u6c42\u3002`; }
  if (id === '19') { const data = await getFeature(runtime, id); if (cmd === '\u6dfb\u52a0' || cmd === 'add') { try { safeUrl(args[1]); } catch (error) { return `RSS URL \u88ab\u62d2\u7edd\uff1a${error.message}`; } await updateFeature(runtime, id, (next) => { next.items = [{ id: randomUUID(), url: args[1] }, ...data.items]; return true; }); return 'RSS \u5df2\u6dfb\u52a0\u3002'; } if (cmd === '\u8bfb\u53d6' || cmd === 'read') { const feed = data.items.find((item) => item.id === args[1]) || data.items[0]; if (!feed) return '\u8bf7\u5148\u6dfb\u52a0 RSS URL\u3002'; try { const raw = await fetchText(feed.url, { maxBytes: 262144 }); return [...raw.matchAll(/<title[^>]*>([^<]+)<\/title>/gi)].slice(0, 8).map((match) => match[1]).join('\n') || '\u672a\u8bfb\u53d6\u5230\u6807\u9898\u3002'; } catch (error) { return `RSS \u8bfb\u53d6\u5931\u8d25\uff1a${error.message}`; } } return show(manifest, data); }
  if (id === '26') { const city = trim(text(args), 80); if (!city) return help(manifest, '<\u57ce\u5e02>'); try { const geo = await fetchJson(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=zh&format=json`, { hosts: ['open-meteo.com'] }); const place = geo.results?.[0]; if (!place) return '\u672a\u627e\u5230\u57ce\u5e02\u3002'; const weather = await fetchJson(`https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&current=temperature_2m,relative_humidity_2m&timezone=Asia%2FShanghai`, { hosts: ['open-meteo.com'] }); return `${place.name}\n\u6e29\u5ea6\uff1a${weather.current?.temperature_2m ?? '-'} C\n\u6e7f\u5ea6\uff1a${weather.current?.relative_humidity_2m ?? '-'}%`; } catch (error) { return `\u5929\u6c14\u670d\u52a1\u4e0d\u53ef\u7528\uff1a${error.message}`; } }
  if (id === '27') { const dictionary = { hello: '\u4f60\u597d', world: '\u4e16\u754c', thanks: '\u8c22\u8c22', '\u4f60\u597d': 'hello' }; return dictionary[text(args).toLowerCase()] || `\u539f\u6587\uff1a${text(args)}\n\u672a\u914d\u7f6e\u5728\u7ebf\u7ffb\u8bd1\u670d\u52a1\uff0c\u4fdd\u7559\u539f\u6587\u3002`; }
  if (id === '28') { const q = encodeURIComponent(text(args)); return `Bing Images: https://www.bing.com/images/search?q=${q}`; }
  if (id === '29' || id === '30') { const valueText = text(args); if (!valueText) return help(manifest, '<\u6587\u672c\u6216\u94fe\u63a5>'); return `QR: https://api.qrserver.com/v1/create-qr-code/?size=${id === '30' ? '500' : '300'}x${id === '30' ? '500' : '300'}&data=${encodeURIComponent(valueText)}\n\u5185\u5bb9\uff1a${valueText}`; }
  if (id === '31') { const data = await getFeature(runtime, id); if (cmd === '\u89e3\u6790' || cmd === 'resolve') return data.links?.[args[1]] ? `\u539f\u94fe\u63a5\uff1a${data.links[args[1]]}` : '\u672a\u627e\u5230\u77ed\u7801\u3002'; const valueText = text(args); try { safeUrl(valueText); } catch { return help(manifest, '<URL> \u6216 \u89e3\u6790 <\u77ed\u7801>'); } const code = randomUUID().slice(0, 8); data.links = { ...(data.links || {}), [code]: valueText }; await updateFeature(runtime, id, (next) => Object.assign(next, data)); return `\u77ed\u7801\uff1a${code}`; }
  if (id === '32') { const query = trim(text(args), 100); if (!query) return help(manifest, '<\u5173\u952e\u8bcd>'); try { const data = await fetchJson(`https://zh.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(query)}`, { hosts: ['wikipedia.org'] }); return [data.title || query, data.extract || '\u6682\u65e0\u6458\u8981', data.content_urls?.desktop?.page || ''].filter(Boolean).join('\n'); } catch (error) { return `\u767e\u79d1\u670d\u52a1\u4e0d\u53ef\u7528\uff1a${error.message}`; } }
  if (id === '33') { const amount = Number(args[0]); const from = String(args[1] || 'CNY').toUpperCase(); const to = String(args[2] || 'USD').toUpperCase(); if (!Number.isFinite(amount)) return help(manifest, '<\u91d1\u989d> <\u6e90\u8d27\u5e01> <\u76ee\u6807\u8d27\u5e01>'); try { const data = await fetchJson(`https://api.frankfurter.app/latest?amount=${amount}&from=${from}&to=${to}`, { hosts: ['frankfurter.app'] }); return `${amount} ${from} ~= ${data.rates?.[to] ?? '-'} ${to}`; } catch (error) { return `\u6c47\u7387\u670d\u52a1\u4e0d\u53ef\u7528\uff1a${error.message}`; } }
  if (id === '34') { const data = await getFeature(runtime, id); data.items = list(data.items); if (cmd === '\u6dfb\u52a0' || cmd === 'add') { if (!value) return help(manifest, '\u6dfb\u52a0 <\u5185\u5bb9>'); const item = { id: randomUUID(), text: value, userId: idOf(event), done: false }; await updateFeature(runtime, id, (next) => { next.items = [item, ...data.items]; return true; }); return `\u5f85\u529e\u5df2\u6dfb\u52a0\uff1a${item.id}`; } if (cmd === '\u5b8c\u6210' || cmd === 'done') { const item = data.items.find((x) => x.id === args[1]); if (!item) return '\u672a\u627e\u5230\u5f85\u529e\u3002'; item.done = true; await updateFeature(runtime, id, (next) => { next.items = data.items; return true; }); return '\u5f85\u529e\u5df2\u5b8c\u6210\u3002'; } return show(manifest, { items: data.items.filter((x) => x.userId === idOf(event) && !x.done) }); }
  if (id === '35') return `${title(manifest)}\n\u5f53\u524d\u65f6\u95f4\uff1a${new Date().toLocaleString('zh-CN', { hour12: false, timeZone: 'Asia/Shanghai' })}`;
  if (id === '36') { try { const url = safeUrl(text(args)); return [`\u534f\u8bae\uff1a${url.protocol}`, `\u4e3b\u673a\uff1a${url.hostname}`, `\u8def\u5f84\uff1a${url.pathname}`, `\u53c2\u6570\uff1a${url.searchParams.size}`].join('\n'); } catch (error) { return `\u89e3\u6790\u5931\u8d25\uff1a${error.message}`; } }
  if (id === '39') { const raw = event.raw?.message; const images = Array.isArray(raw) ? raw.filter((item) => item?.type === 'image').map((item) => item.url || item.file).filter(Boolean) : []; const valueText = images.join('\n') || value; if (!valueText) return '\u6d88\u606f\u4e2d\u6ca1\u6709\u53ef\u6536\u85cf\u56fe\u7247\u3002'; await updateFeature(runtime, id, (data) => { data.items.unshift({ id: randomUUID(), text: valueText, userId: idOf(event) }); return true; }); return '\u56fe\u7247\u5df2\u6536\u85cf\u3002'; }
  if (id === '44') { const data = await getFeature(runtime, id); data.users = data.users || {}; const user = data.users[idOf(event)] || { points: 0 }; const day = new Date().toISOString().slice(0, 10); if (user.day === day) return `\u4eca\u5929\u5df2\u7b7e\u5230\uff0c\u79ef\u5206\uff1a${user.points}`; user.day = day; user.points += 1 + Math.floor(Math.random() * 5); data.users[idOf(event)] = user; await updateFeature(runtime, id, (next) => Object.assign(next, data)); return `\u7b7e\u5230\u6210\u529f\uff0c\u79ef\u5206\uff1a${user.points}`; }
  if (id === '49') { const data = await getFeature(runtime, id); data.events = data.events || {}; const key = trim(args[1] || 'default', 80); data.events[key] = data.events[key] || { open: true, users: [] }; const item = data.events[key]; if (cmd === '\u5173\u95ed' || cmd === 'close') item.open = false; else if (cmd === '\u5f00\u542f' || cmd === 'open') item.open = true; else if (cmd === '\u53c2\u52a0' || cmd === 'join') { if (!item.open) return '\u6d3b\u52a8\u5df2\u5173\u95ed\u3002'; if (!item.users.includes(idOf(event))) item.users.push(idOf(event)); } else return `\u6d3b\u52a8 ${key}\n\u72b6\u6001\uff1a${item.open ? '\u8fdb\u884c\u4e2d' : '\u5df2\u5173\u95ed'}\n\u4eba\u6570\uff1a${item.users.length}`; await updateFeature(runtime, id, (next) => Object.assign(next, data)); return `\u6d3b\u52a8 ${key} \u5df2\u66f4\u65b0\u3002`; }
  if (id === '50') { const data = await getFeature(runtime, id); data.users = data.users || {}; const item = data.users[idOf(event)] || {}; const day = new Date().toISOString().slice(0, 10); if (item.day !== day) { item.day = day; item.task = ['\u5b8c\u6210\u4e00\u6b21\u7b7e\u5230', '\u6dfb\u52a0\u4e00\u6761\u5f85\u529e', '\u53d1\u9001\u4e00\u6761\u6709\u5e2e\u52a9\u7684\u6d88\u606f'][Math.floor(Math.random() * 3)]; item.done = false; } if (cmd === '\u5b8c\u6210' || cmd === 'done') item.done = true; data.users[idOf(event)] = item; await updateFeature(runtime, id, (next) => Object.assign(next, data)); return `\u4eca\u65e5\u4efb\u52a1\uff1a${item.task}\n\u72b6\u6001\uff1a${item.done ? '\u5df2\u5b8c\u6210' : '\u8fdb\u884c\u4e2d'}`; }
  const data = await getFeature(runtime, id); data.items = list(data.items); if (cmd === '\u6dfb\u52a0' || cmd === 'add' || cmd === '\u8ba2\u9605' || cmd === 'join') { if (!value) return help(manifest, '\u6dfb\u52a0 <\u5185\u5bb9>'); const item = { id: randomUUID(), text: value, userId: idOf(event), groupId: scopeOf(event), time: Date.now() }; await updateFeature(runtime, id, (next) => { next.items = [item, ...data.items].slice(0, 500); return true; }); return `\u5df2\u8bb0\u5f55\uff1a${item.id}`; } if (cmd === '\u5220\u9664' || cmd === 'del') { await updateFeature(runtime, id, (next) => { next.items = data.items.filter((item) => item.id !== args[1]); return true; }); return '\u8bb0\u5f55\u5df2\u5220\u9664\u3002'; } return show(manifest, data);
}

export async function scanFeature(manifest, event, runtime) {
  if (!['15', '16', '41'].includes(manifest.id)) return false;
  const value = String(event.message || ''); if (!value || value.startsWith('#\u4e91\u9526')) return false;
  const data = await getFeature(runtime, manifest.id); const words = list(data.items);
  if (manifest.id === '41') { const rule = words.find((item) => item?.trigger && value.includes(item.trigger)); if (rule && typeof event.reply === 'function') await event.reply(rule.response); return false; }
  const hit = words.find((item) => String(item).length && value.toLowerCase().includes(String(item).toLowerCase()));
  const ad = manifest.id === '16' && /https?:\/\//i.test(value);
  if (hit || ad) { await runtime.audit.record({ action: 'message.block', featureId: manifest.id, userId: idOf(event), groupId: event.groupId }); return true; }
  return false;
}

